### ISSUE TITLE
Dynamically Add Menu Items/Extra Data

### ISSUE THREAD

**Issue by dmarciano** [stavroskasidis/BlazorContextMenu#50]
I have a grid which displays a list of clients.  I want to add a context menu to each row which has options such as "Create Project", "Invoice Client" etc and then when this menu item is clicked, it navigates the users to the appropriate page.  For this to work though, I need to be able to build the menu items dynamically so I can add extra data (e.g. the client ID from the grid) so that it can be included in the query string to the appropriate page.

**Comment by stavroskasidis** [comment]
This is possible using the "OnAppearing" events. You add all the possible items that can appear on the menu, then show/hide them depending on the item clicked.

Please refer to this example for details:
https://blazor-context-menu-demo.azurewebsites.net/dynamicitems

**Comment by stavroskasidis** [comment]
I think I misunderstood what you want to achieve.
You want during the click event to do stuff depending on the clicked item, like get the id of the row.

Right now the way to deal with this is by using the `ContextMenuTargetId` from the `ItemClickEventArgs`. Then you can, for example use js interop to get the row index or something that will help you identify the current "client" clicked.

You can see a sample here:
https://blazor-context-menu-demo.azurewebsites.net/gridsample

I do want to add "Extra Data" passed from the `ContextMenuTrigger`, however due to current Blazor limitations, it would be limited to `string`, so I am waiting a bit before adding something that will change in the future.

**Comment by stavroskasidis** [comment]
The data feature is now implemented in 0.20.

Check the sample again to see how to use:
https://blazor-context-menu-demo.azurewebsites.net/gridsample
